### ISSUE TITLE
Not bug but suggestion

### ISSUE THREAD

**Issue by Technorocker** [YoussefLasheen/flurry_navigation#1]
I just came across your plugin and think it looks very elegant. I'm trying to get it setup for my app and I'm wondering why you chose to use icons with strings referencing the asset folder instead of using actual IconData?

 Is there a way to use flutters icons and not have to download a bunch of them into the asset folder?

**Comment by YoussefLasheen** [comment]
The package was made when it was a bit difficult to import your own icons so I opted to just use images to make it simpler. but now there are a lot of packages for icons. 

You're right it needs to be changed. Its a simple fix if you want to have a go at it:).  Pull requests are always welcome.

**Comment by Technorocker** [comment]
Thanks for the quick reply. unfortunately, I was using a bottom nav bar and I was trying to switch over to your nav system but with the way you have implemented the screens I can't incorporate my stateful widget based screens into it as I need init state and a way to setup dynamic content for the page. 

The style looks great though and would be very appeasing for simple page navigation.
